User can search by ingredient & view a list of recipes
CraftAcademy/not_so_trivial_recepies pull request #8
Opened 2019-10-08 13:37 UTC by beccaburns

[PT-Link](https://www.pivotaltracker.com/story/show/168978853)
[PT-Link](https://www.pivotaltracker.com/story/show/168979054)

## User can search by ingredient & view a list of the recipes

## In this PR
- We created the feature and corresponding step definitions for this user story

## What we learned
- We generated a recipe controller with a haml file that presents the search bar where users can input ingredients and view recipes from the API
- We learned how to integrate the API through the module to the index to present the results needed
- Continued learning about how to write haml and corresponding styling
- Deeper understanding of paths and how data flows

![LandingPage_NotSoTrivial](https://user-images.githubusercontent.com/53613884/66400018-fb535780-e9e0-11e9-94ca-868f0b922bfd.jpg)

![Screen Shot 2019-10-08 at 3 35 49 PM](https://user-images.githubusercontent.com/53613884/66400264-6ef56480-e9e1-11e9-9b85-288f099c6df0.png)

![Screen Shot 2019-10-08 at 3 36 02 PM](https://user-images.githubusercontent.com/53613884/66400270-73ba1880-e9e1-11e9-85c6-ec6d0a664cdc.png)

2019-10-08 13:43 UTC, faraznaeem commented
MERGE conflicts!

2019-10-08 13:46 UTC, beccaburns commented
> MERGE conflicts!

2019-10-08 13:58 UTC, piavW approved these changes

2019-10-08 13:58 UTC, piavW commented on app/controllers/recipes_controller.rb
> +
Please remove empty row

2019-10-08 13:58 UTC, piavW commented on features/support/env.rb
Do you have database cleaner? No need to have the code-block if we don't. :)

2019-10-08 14:40 UTC, AlexSaxena approved these changes

2019-10-08 14:41 UTC, yasmineezequiel approved these changes

2019-10-09 07:14 UTC, faraznaeem requested changes

2019-10-09 07:14 UTC, faraznaeem commented on app/views/layouts/mailer.html.haml
> +    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
did you add back ha hash rocket?

2019-10-09 07:14 UTC, faraznaeem commented on features/user_can_sign_up_for_an_account.feature
> +    Then I should see "Logged in as berg@sten.com"
This feature is out of scope

2019-10-09 07:24 UTC, faraznaeem approved these changes

2019-10-09 07:25 UTC, merged